# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
    - mainline

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'hakchi_gui.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:

- checkout: self
  submodules: true
  persistCredentials: true

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: nsis@1
  inputs:
    scriptFile: 
    justInclude: 'yes'
    includeMorePlugins: 'no'

- task: VSBuild@1
  inputs:
    solution: 'hakchi_gui.sln'
    configuration: 'Installer'
    platform: 'Any CPU'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/bin/'
    Contents: 'hakchi2-ce-*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true
    preserveTimestamp: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: '$(Build.SourceVersion)'
    publishLocation: 'Container'